// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubscribeReq.proto

package example.book.codec.protobuf.pojo;

public final class SubscribeReqProto {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_example_book_codec_proto_SubscribeReq_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_example_book_codec_proto_SubscribeReq_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\022SubscribeReq.proto\022\030example.book.codec" +
                        ".proto\"W\n\014SubscribeReq\022\020\n\010subReqID\030\001 \001(\005" +
                        "\022\020\n\010username\030\002 \001(\t\022\022\n\nproductNme\030\003 \001(\t\022\017" +
                        "\n\007address\030\004 \003(\tB5\n example.book.codec.pr" +
                        "otobuf.pojoB\021SubscribeReqProtob\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_example_book_codec_proto_SubscribeReq_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_example_book_codec_proto_SubscribeReq_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_example_book_codec_proto_SubscribeReq_descriptor,
                new java.lang.String[]{"SubReqID", "Username", "ProductNme", "Address",});
    }

    private SubscribeReqProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface SubscribeReqOrBuilder extends
            // @@protoc_insertion_point(interface_extends:example.book.codec.proto.SubscribeReq)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 subReqID = 1;</code>
         *
         * @return The subReqID.
         */
        int getSubReqID();

        /**
         * <code>string username = 2;</code>
         *
         * @return The username.
         */
        java.lang.String getUsername();

        /**
         * <code>string username = 2;</code>
         *
         * @return The bytes for username.
         */
        com.google.protobuf.ByteString
        getUsernameBytes();

        /**
         * <code>string productNme = 3;</code>
         *
         * @return The productNme.
         */
        java.lang.String getProductNme();

        /**
         * <code>string productNme = 3;</code>
         *
         * @return The bytes for productNme.
         */
        com.google.protobuf.ByteString
        getProductNmeBytes();

        /**
         * <code>repeated string address = 4;</code>
         *
         * @return A list containing the address.
         */
        java.util.List<java.lang.String>
        getAddressList();

        /**
         * <code>repeated string address = 4;</code>
         *
         * @return The count of address.
         */
        int getAddressCount();

        /**
         * <code>repeated string address = 4;</code>
         *
         * @param index The index of the element to return.
         * @return The address at the given index.
         */
        java.lang.String getAddress(int index);

        /**
         * <code>repeated string address = 4;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the address at the given index.
         */
        com.google.protobuf.ByteString
        getAddressBytes(int index);
    }

    /**
     * Protobuf type {@code example.book.codec.proto.SubscribeReq}
     */
    public static final class SubscribeReq extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:example.book.codec.proto.SubscribeReq)
            SubscribeReqOrBuilder {
        public static final int SUBREQID_FIELD_NUMBER = 1;
        public static final int USERNAME_FIELD_NUMBER = 2;
        public static final int PRODUCTNME_FIELD_NUMBER = 3;
        public static final int ADDRESS_FIELD_NUMBER = 4;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:example.book.codec.proto.SubscribeReq)
        private static final example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<SubscribeReq>
                PARSER = new com.google.protobuf.AbstractParser<SubscribeReq>() {
            @java.lang.Override
            public SubscribeReq parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new SubscribeReq(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq();
        }

        private int subReqID_;
        private volatile java.lang.Object username_;
        private volatile java.lang.Object productNme_;
        private com.google.protobuf.LazyStringList address_;
        private byte memoizedIsInitialized = -1;

        // Use SubscribeReq.newBuilder() to construct.
        private SubscribeReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private SubscribeReq() {
            username_ = "";
            productNme_ = "";
            address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        }

        private SubscribeReq(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            subReqID_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            username_ = s;
                            break;
                        }
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();

                            productNme_ = s;
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                address_ = new com.google.protobuf.LazyStringArrayList();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            address_.add(s);
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) != 0)) {
                    address_ = address_.getUnmodifiableView();
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return example.book.codec.protobuf.pojo.SubscribeReqProto.internal_static_example_book_codec_proto_SubscribeReq_descriptor;
        }

        public static example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<SubscribeReq> parser() {
            return PARSER;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new SubscribeReq();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return example.book.codec.protobuf.pojo.SubscribeReqProto.internal_static_example_book_codec_proto_SubscribeReq_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq.class, example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq.Builder.class);
        }

        /**
         * <code>int32 subReqID = 1;</code>
         *
         * @return The subReqID.
         */
        @java.lang.Override
        public int getSubReqID() {
            return subReqID_;
        }

        /**
         * <code>string username = 2;</code>
         *
         * @return The username.
         */
        @java.lang.Override
        public java.lang.String getUsername() {
            java.lang.Object ref = username_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                username_ = s;
                return s;
            }
        }

        /**
         * <code>string username = 2;</code>
         *
         * @return The bytes for username.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getUsernameBytes() {
            java.lang.Object ref = username_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                username_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string productNme = 3;</code>
         *
         * @return The productNme.
         */
        @java.lang.Override
        public java.lang.String getProductNme() {
            java.lang.Object ref = productNme_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                productNme_ = s;
                return s;
            }
        }

        /**
         * <code>string productNme = 3;</code>
         *
         * @return The bytes for productNme.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getProductNmeBytes() {
            java.lang.Object ref = productNme_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                productNme_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>repeated string address = 4;</code>
         *
         * @return A list containing the address.
         */
        public com.google.protobuf.ProtocolStringList
        getAddressList() {
            return address_;
        }

        /**
         * <code>repeated string address = 4;</code>
         *
         * @return The count of address.
         */
        public int getAddressCount() {
            return address_.size();
        }

        /**
         * <code>repeated string address = 4;</code>
         *
         * @param index The index of the element to return.
         * @return The address at the given index.
         */
        public java.lang.String getAddress(int index) {
            return address_.get(index);
        }

        /**
         * <code>repeated string address = 4;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the address at the given index.
         */
        public com.google.protobuf.ByteString
        getAddressBytes(int index) {
            return address_.getByteString(index);
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (subReqID_ != 0) {
                output.writeInt32(1, subReqID_);
            }
            if (!getUsernameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, username_);
            }
            if (!getProductNmeBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, productNme_);
            }
            for (int i = 0; i < address_.size(); i++) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, address_.getRaw(i));
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (subReqID_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, subReqID_);
            }
            if (!getUsernameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, username_);
            }
            if (!getProductNmeBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, productNme_);
            }
            {
                int dataSize = 0;
                for (int i = 0; i < address_.size(); i++) {
                    dataSize += computeStringSizeNoTag(address_.getRaw(i));
                }
                size += dataSize;
                size += 1 * getAddressList().size();
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq)) {
                return super.equals(obj);
            }
            example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq other = (example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq) obj;

            if (getSubReqID()
                    != other.getSubReqID()) return false;
            if (!getUsername()
                    .equals(other.getUsername())) return false;
            if (!getProductNme()
                    .equals(other.getProductNme())) return false;
            if (!getAddressList()
                    .equals(other.getAddressList())) return false;
            return unknownFields.equals(other.unknownFields);
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + SUBREQID_FIELD_NUMBER;
            hash = (53 * hash) + getSubReqID();
            hash = (37 * hash) + USERNAME_FIELD_NUMBER;
            hash = (53 * hash) + getUsername().hashCode();
            hash = (37 * hash) + PRODUCTNME_FIELD_NUMBER;
            hash = (53 * hash) + getProductNme().hashCode();
            if (getAddressCount() > 0) {
                hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
                hash = (53 * hash) + getAddressList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<SubscribeReq> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code example.book.codec.proto.SubscribeReq}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:example.book.codec.proto.SubscribeReq)
                example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReqOrBuilder {
            private int bitField0_;
            private int subReqID_;
            private java.lang.Object username_ = "";
            private java.lang.Object productNme_ = "";
            private com.google.protobuf.LazyStringList address_ = com.google.protobuf.LazyStringArrayList.EMPTY;

            // Construct using example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return example.book.codec.protobuf.pojo.SubscribeReqProto.internal_static_example_book_codec_proto_SubscribeReq_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return example.book.codec.protobuf.pojo.SubscribeReqProto.internal_static_example_book_codec_proto_SubscribeReq_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq.class, example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                subReqID_ = 0;

                username_ = "";

                productNme_ = "";

                address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return example.book.codec.protobuf.pojo.SubscribeReqProto.internal_static_example_book_codec_proto_SubscribeReq_descriptor;
            }

            @java.lang.Override
            public example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq getDefaultInstanceForType() {
                return example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq.getDefaultInstance();
            }

            @java.lang.Override
            public example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq build() {
                example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq buildPartial() {
                example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq result = new example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq(this);
                int from_bitField0_ = bitField0_;
                result.subReqID_ = subReqID_;
                result.username_ = username_;
                result.productNme_ = productNme_;
                if (((bitField0_ & 0x00000001) != 0)) {
                    address_ = address_.getUnmodifiableView();
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.address_ = address_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq) {
                    return mergeFrom((example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq other) {
                if (other == example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq.getDefaultInstance())
                    return this;
                if (other.getSubReqID() != 0) {
                    setSubReqID(other.getSubReqID());
                }
                if (!other.getUsername().isEmpty()) {
                    username_ = other.username_;
                    onChanged();
                }
                if (!other.getProductNme().isEmpty()) {
                    productNme_ = other.productNme_;
                    onChanged();
                }
                if (!other.address_.isEmpty()) {
                    if (address_.isEmpty()) {
                        address_ = other.address_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureAddressIsMutable();
                        address_.addAll(other.address_);
                    }
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (example.book.codec.protobuf.pojo.SubscribeReqProto.SubscribeReq) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>int32 subReqID = 1;</code>
             *
             * @return The subReqID.
             */
            @java.lang.Override
            public int getSubReqID() {
                return subReqID_;
            }

            /**
             * <code>int32 subReqID = 1;</code>
             *
             * @param value The subReqID to set.
             * @return This builder for chaining.
             */
            public Builder setSubReqID(int value) {

                subReqID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 subReqID = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSubReqID() {

                subReqID_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>string username = 2;</code>
             *
             * @return The username.
             */
            public java.lang.String getUsername() {
                java.lang.Object ref = username_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    username_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string username = 2;</code>
             *
             * @param value The username to set.
             * @return This builder for chaining.
             */
            public Builder setUsername(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                username_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string username = 2;</code>
             *
             * @return The bytes for username.
             */
            public com.google.protobuf.ByteString
            getUsernameBytes() {
                java.lang.Object ref = username_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    username_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string username = 2;</code>
             *
             * @param value The bytes for username to set.
             * @return This builder for chaining.
             */
            public Builder setUsernameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                username_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string username = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearUsername() {

                username_ = getDefaultInstance().getUsername();
                onChanged();
                return this;
            }

            /**
             * <code>string productNme = 3;</code>
             *
             * @return The productNme.
             */
            public java.lang.String getProductNme() {
                java.lang.Object ref = productNme_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    productNme_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string productNme = 3;</code>
             *
             * @param value The productNme to set.
             * @return This builder for chaining.
             */
            public Builder setProductNme(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                productNme_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string productNme = 3;</code>
             *
             * @return The bytes for productNme.
             */
            public com.google.protobuf.ByteString
            getProductNmeBytes() {
                java.lang.Object ref = productNme_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    productNme_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string productNme = 3;</code>
             *
             * @param value The bytes for productNme to set.
             * @return This builder for chaining.
             */
            public Builder setProductNmeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                productNme_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string productNme = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearProductNme() {

                productNme_ = getDefaultInstance().getProductNme();
                onChanged();
                return this;
            }

            private void ensureAddressIsMutable() {
                if (!((bitField0_ & 0x00000001) != 0)) {
                    address_ = new com.google.protobuf.LazyStringArrayList(address_);
                    bitField0_ |= 0x00000001;
                }
            }

            /**
             * <code>repeated string address = 4;</code>
             *
             * @return A list containing the address.
             */
            public com.google.protobuf.ProtocolStringList
            getAddressList() {
                return address_.getUnmodifiableView();
            }

            /**
             * <code>repeated string address = 4;</code>
             *
             * @return The count of address.
             */
            public int getAddressCount() {
                return address_.size();
            }

            /**
             * <code>repeated string address = 4;</code>
             *
             * @param index The index of the element to return.
             * @return The address at the given index.
             */
            public java.lang.String getAddress(int index) {
                return address_.get(index);
            }

            /**
             * <code>repeated string address = 4;</code>
             *
             * @param index The index of the value to return.
             * @return The bytes of the address at the given index.
             */
            public com.google.protobuf.ByteString
            getAddressBytes(int index) {
                return address_.getByteString(index);
            }

            /**
             * <code>repeated string address = 4;</code>
             *
             * @param index The index to set the value at.
             * @param value The address to set.
             * @return This builder for chaining.
             */
            public Builder setAddress(
                    int index, java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureAddressIsMutable();
                address_.set(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string address = 4;</code>
             *
             * @param value The address to add.
             * @return This builder for chaining.
             */
            public Builder addAddress(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureAddressIsMutable();
                address_.add(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string address = 4;</code>
             *
             * @param values The address to add.
             * @return This builder for chaining.
             */
            public Builder addAllAddress(
                    java.lang.Iterable<java.lang.String> values) {
                ensureAddressIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, address_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string address = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearAddress() {
                address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string address = 4;</code>
             *
             * @param value The bytes of the address to add.
             * @return This builder for chaining.
             */
            public Builder addAddressBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                ensureAddressIsMutable();
                address_.add(value);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:example.book.codec.proto.SubscribeReq)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
